import { Colors, Gradients, Shadows } from "../constants/colors";

export const styles = {
  container: {
    display: 'flex',
    minHeight: '100vh',
    background: 'transparent',
    fontFamily: '"Sarabun", sans-serif'
  },
  sidebar: {
    width: '260px',
    background: '#0F172A',
    borderRight: '1px solid rgba(255,255,255,0.08)',
    backdropFilter: 'blur(14px)',
    position: 'fixed',
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    paddingBottom: '28px',
    zIndex: 100,
    boxShadow: Shadows.sidebar
  },
  mainArea: { flex: 1, minWidth: 0, overflowX: 'clip' },
  header: {
    background: '#ffffff',
    borderBottom: '1px solid #e2e8f0',
    textAlign: 'right'
  },
  headerTitle: { fontSize: '18px', fontWeight: '800', color: '#1E293B', display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: '8px' },
  scrollContent: {},
  pageLayout: { maxWidth: '1200px', margin: '0 auto' },
  logo: {
    fontSize: '27px',
    fontWeight: '900',
    color: Colors.white,
    padding: '38px 30px',
    letterSpacing: '-0.4px',
  },
  navLink: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: '13px 24px',
    margin: '4px 12px',
    borderRadius: '14px',
    fontWeight: '800',
    fontSize: '15px'
  },
  statGrid: { marginBottom: '25px' },
  statCard: {
    background: Colors.white,
    padding: '20px',
    borderRadius: '22px',
    border: `1px solid ${Colors.border}`,
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    boxShadow: '0 4px 18px rgba(15, 23, 42, 0.08), 0 1px 4px rgba(15, 23, 42, 0.05)'
  },
  statCardContent: {
    flex: 1,
    minWidth: 0,
  },
  statIcon: { fontSize: '24px', background: Colors.bgSoft, padding: '10px', borderRadius: '12px' },
  statLabel: { color: Colors.textGray, fontSize: '13px' },
  mainGrid: {},
  card: {
    background: Colors.white,
    borderRadius: '26px',
    padding: '26px',
    border: `1px solid ${Colors.border}`,
    boxShadow: '0 4px 18px rgba(15, 23, 42, 0.08), 0 1px 4px rgba(15, 23, 42, 0.05)',
  },
  cardTitle: { fontWeight: '900', fontSize: '18px', color: Colors.secondary, display: 'flex', alignItems: 'center', gap: '10px', letterSpacing: '-0.2px' },
  searchToggleGroup: { display: 'flex', gap: '10px', marginBottom: '20px' },
  activeModeBtn: {
    flex: 1,
    padding: '12px',
    borderRadius: '12px',
    border: 'none',
    background: Gradients.primary,
    color: 'white',
    fontWeight: '800',
    cursor:'pointer',
    boxShadow: Shadows.primarySoft
  },
  inactiveModeBtn: { flex: 1, padding: '12px', borderRadius: '12px', border: `1px solid ${Colors.border}`, background: Colors.bgSoft, fontWeight: '800', color: Colors.textGray, cursor:'pointer' },
  inputSearchBox: { width: '100%', padding: '13px 14px', borderRadius: '12px', border: `1px solid ${Colors.border}`, background: 'rgba(255,255,255,0.9)', outline:'none', boxSizing: 'border-box' },
  customFoodToggle: {
    marginTop: '12px',
    width: '100%',
    padding: '10px 12px',
    borderRadius: '12px',
    border: `1px dashed ${Colors.accent}`,
    background: Colors.aiLight,
    color: Colors.accent,
    fontWeight: '800',
    fontSize: '13px',
    cursor: 'pointer'
  },
  customFoodPanel: {
    marginTop: '12px',
    padding: '14px',
    borderRadius: '16px',
    border: `1px solid ${Colors.border}`,
    background: Colors.bgSoft
  },
  customFoodTitle: { fontSize: '14px', fontWeight: '900', color: '#334155', marginBottom: '12px' },
  customFoodField: { marginBottom: '10px' },
  customFoodLabel: { display: 'block', marginBottom: '6px', fontSize: '12px', fontWeight: '800', color: '#64748b' },
  customFoodInput: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '10px',
    border: '1px solid #e2e8f0',
    background: '#ffffff',
    outline: 'none',
    boxSizing: 'border-box',
    fontSize: '14px'
  },
  customFoodGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: '10px' },
  customFoodActions: { display: 'flex', gap: '10px', marginTop: '12px' },
  customFoodSubmitBtn: {
    flex: 1,
    padding: '11px',
    borderRadius: '12px',
    border: 'none',
    background: Gradients.primary,
    color: '#ffffff',
    fontWeight: '900',
    cursor: 'pointer'
  },
  customFoodCancelBtn: {
    padding: '11px 16px',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    background: '#ffffff',
    color: '#64748b',
    fontWeight: '800',
    cursor: 'pointer'
  },
  customFoodHint: { marginTop: '10px', fontSize: '12px', color: Colors.textGray, textAlign: 'center' },
  customFoodHintText: { margin: '0 0 12px', fontSize: '12px', color: Colors.textGray, lineHeight: 1.5 },
  customFoodPreview: {
    marginBottom: '12px',
    padding: '12px',
    borderRadius: '12px',
    background: '#f8fafc',
    border: '1px solid #e2e8f0',
    textAlign: 'center'
  },
  customFoodPreviewTitle: { fontSize: '11px', fontWeight: '800', color: '#64748b', textTransform: 'uppercase' },
  customFoodPreviewCal: { marginTop: '6px', fontSize: '22px', fontWeight: '900', color: Colors.primary },
  customFoodPreviewMacros: { marginTop: '4px', fontSize: '12px', fontWeight: '700', color: '#475569' },
  customFoodIngredientList: {
    marginTop: '10px',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  customFoodIngredientChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 8px',
    borderRadius: '999px',
    background: '#ffffff',
    border: '1px solid #e2e8f0',
    fontSize: '11px',
    fontWeight: '700',
    color: '#475569',
  },
  activityModalTitle: { fontSize: '16px', fontWeight: '900', color: Colors.secondary },
  activityModalSubtitle: { marginTop: '4px', fontSize: '14px', fontWeight: '700', color: Colors.primary },
  activityIntensitySelect: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '10px',
    border: '1px solid #e2e8f0',
    background: '#ffffff',
    outline: 'none',
    boxSizing: 'border-box',
    fontSize: '14px',
    fontWeight: '600',
    color: Colors.textDark,
  },
  activityModalPreview: {
    marginTop: '4px',
    marginBottom: '14px',
    padding: '14px',
    borderRadius: '14px',
    background: 'var(--nutri-bg-soft)',
    border: '1px solid var(--nutri-border)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
  },
  activityModalPreviewLabel: { fontSize: '12px', fontWeight: '800', color: Colors.textGray },
  activityModalPreviewValue: { fontSize: '24px', fontWeight: '900', color: Colors.primary },
  activityModalActions: { display: 'flex', gap: '10px' },
  portionTypeGroup: { display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: '8px' },
  portionTypeHint: { margin: '8px 0 0', fontSize: '11px', fontWeight: '600', color: Colors.textGray, lineHeight: 1.4 },
  portionPreviewMacros: { marginTop: '6px', fontSize: '12px', fontWeight: '700', color: Colors.textGray },
  portionPreviewNote: { marginTop: '4px', fontSize: '11px', fontWeight: '800', color: Colors.accent },
  activityLogList: { marginTop: '16px' },
  activityLogTitle: { fontSize: '13px', fontWeight: '900', color: Colors.secondary, marginBottom: '10px' },
  activityLogRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '10px',
    padding: '12px 0',
    borderBottom: '1px dashed #e5e7eb',
  },
  activityLogMeta: { fontSize: '12px', color: Colors.textGray, marginTop: '3px', fontWeight: '600' },
  activityRecordBadge: {
    marginLeft: '8px',
    fontSize: '11px',
    fontWeight: '800',
    color: Colors.success,
    background: '#d1fae5',
    padding: '2px 8px',
    borderRadius: '999px',
  },
  customMealBadge: {
    marginLeft: '8px',
    fontSize: '11px',
    fontWeight: '800',
    color: Colors.accent,
    background: Colors.accentMuted,
    padding: '2px 8px',
    borderRadius: '999px'
  },
  searchResultContainer: { maxHeight: '200px', overflowY: 'auto', marginTop: '10px' },
  searchItem: { display: 'flex', justifyContent: 'space-between', padding: '12px 8px', borderBottom: '1px dashed #e5e7eb', alignItems: 'center' },
  btnAdd: { background: Colors.primary, color: 'white', border: 'none', borderRadius: '8px', padding: '6px', cursor:'pointer', boxShadow: Shadows.primarySoft },
  analyzedMealRow: { display: 'flex', flexDirection: 'column', gap: '5px', padding: '10px 8px', borderBottom: '1px dashed #e5e7eb', boxSizing: 'border-box' },
  mealSectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    gap: '10px',
    marginBottom: '8px',
    flexWrap: 'wrap',
  },
  mealSectionTotal: { display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' },
  mealSectionNet: { fontSize: '13px', fontWeight: '900', color: Colors.secondary },
  mealSectionBurn: { fontSize: '12px', fontWeight: '800', color: Colors.success },
  macroPillRow: { display: 'flex', gap: '12px', background: Colors.bgSoft, padding: '5px 12px', borderRadius: '20px', fontSize: '12px', fontWeight: 'bold', width: 'fit-content' },
  mealInsightText: { fontSize: '15px', color: '#334155', fontWeight: '600', lineHeight: '1.65', letterSpacing: '0.1px' },
  aiCardShell: {
    borderRadius: '28px',
    padding: '14px',
    background: Gradients.aiShell,
    border: '1px solid var(--nutri-accent-alpha-15)',
    boxShadow: '0 14px 30px rgba(15, 23, 42, 0.08)'
  },
  aiCardHeader: { display: 'flex', gap: '12px', alignItems: 'center', padding: '6px 6px 10px 6px' },
  aiCardHeaderIcon: {
    width: '44px',
    height: '44px',
    borderRadius: '14px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: Colors.accent,
    background: Colors.white,
    border: `1px solid ${Colors.border}`,
    boxShadow: '0 10px 22px rgba(15, 23, 42, 0.06)'
  },
  aiCardHeaderTitle: { fontSize: '16px', fontWeight: '900', color: Colors.secondary, letterSpacing: '-0.2px' },
  aiCardHeaderSub: { marginTop: '2px', fontSize: '12px', fontWeight: '700', color: '#64748b' },
  aiPlanCard: {
    marginTop: '2px',
    background: 'rgba(255,255,255,0.92)',
    padding: '16px',
    borderRadius: '22px',
    border: '1px solid rgba(226,232,240,0.9)',
    boxShadow: '0 10px 24px rgba(15, 23, 42, 0.06)',
    backdropFilter: 'blur(6px)'
  },
  aiPlanTopRow: { display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' },
  aiPlanBadge: { fontSize: '11px', fontWeight: '900', letterSpacing: '0.6px', textTransform: 'uppercase', color: Colors.accent, background: Colors.accentMuted, border: `1px solid ${Colors.border}`, padding: '4px 10px', borderRadius: '999px' },
  aiPlanTitle: { fontSize: '12px', fontWeight: '800', color: Colors.textGray, textTransform: 'uppercase' },
  aiPlanHeadline: { marginTop: '12px', fontSize: '18px', fontWeight: '900', color: Colors.secondary, lineHeight: '1.25', letterSpacing: '-0.2px' },
  aiPlanSubline: { marginTop: '6px', fontSize: '13px', fontWeight: '700', color: '#475569', lineHeight: '1.45' },
  aiChipRow: {
    marginTop: '12px',
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(96px, 1fr))',
    gap: '10px',
  },
  aiChip: {
    minWidth: 0,
    borderRadius: '14px',
    padding: '10px 10px',
    background: '#f8fafc',
    border: '1px solid #e2e8f0',
  },
  aiChipLabel: { fontSize: '11px', fontWeight: '900', color: '#64748b', textTransform: 'uppercase' },
  aiChipValue: { marginTop: '6px', fontSize: '14px', fontWeight: '900', color: '#0f172a' },
  aiPlanGrid2: { marginTop: '12px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' },
  aiPlanPanel: { borderRadius: '16px', padding: '12px', border: `1px solid ${Colors.border}`, background: '#ffffff' },
  aiPlanPanelTitle: { fontSize: '11px', fontWeight: '900', color: Colors.secondary, textTransform: 'uppercase' },
  aiPlanPanelBody: { marginTop: '8px', fontSize: '13px', fontWeight: '700', color: '#334155', lineHeight: '1.55' },
  aiMacroMeterWrap: { marginTop: '12px', display: 'flex', flexDirection: 'column', gap: '10px' },
  aiMacroMeterRow: { display: 'flex', flexDirection: 'column', gap: '6px' },
  aiMacroMeterTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' },
  aiMacroMeterLabel: { fontSize: '12px', fontWeight: '900' },
  aiMacroMeterPct: { fontSize: '12px', fontWeight: '900', color: '#64748b' },
  aiMacroMeterTrack: { height: '8px', borderRadius: '999px', overflow: 'hidden' },
  aiMacroMeterFill: { height: '100%', borderRadius: '999px' },
  aiMacroSummary: {
    marginTop: '12px',
    padding: '12px 14px',
    borderRadius: '14px',
    background: '#f8fafc',
    border: '1px solid #e2e8f0',
  },
  aiMacroSummaryTitle: {
    fontSize: '11px',
    fontWeight: '900',
    color: Colors.secondary,
    textTransform: 'uppercase',
    marginBottom: '8px',
  },
  aiMacroSummaryBody: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#334155',
    lineHeight: 1.65,
  },
  aiPlanActionChip: { marginTop: '10px', display: 'block', width: '100%', boxSizing: 'border-box', textAlign: 'center', padding: '10px 12px', borderRadius: '12px', fontSize: '12px', fontWeight: '900' },
  btnDelete: { background: '#fef2f2', border: '1px solid #fecaca', color: Colors.danger, width: '28px', height: '28px', borderRadius: '8px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  totalFooter: { marginTop: '20px', textAlign: 'right', fontSize: '24px', fontWeight: '900', color: Colors.primary, letterSpacing: '-0.4px' },
  dailySummaryBox: {
    marginTop: '24px',
    padding: '18px',
    borderRadius: '18px',
    background: Gradients.summary,
    border: '1px solid var(--nutri-accent-alpha-15)',
  },
  dailySummaryTitle: {
    fontSize: '14px',
    fontWeight: '900',
    color: Colors.accent,
    marginBottom: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  dailySummaryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '10px',
    marginBottom: '14px',
  },
  dailySummaryStat: {
    padding: '12px 14px',
    borderRadius: '14px',
    background: 'rgba(255,255,255,0.85)',
    border: `1px solid ${Colors.border}`,
  },
  dailySummaryStatLabel: { fontSize: '11px', fontWeight: '800', color: Colors.textGray, textTransform: 'uppercase' },
  dailySummaryStatValue: { marginTop: '4px', fontSize: '18px', fontWeight: '900', color: '#1e293b' },
  dailySummaryMealRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 0',
    borderBottom: '1px dashed #cbd5e1',
    fontSize: '13px',
    fontWeight: '700',
    color: '#475569',
  },
  dailySummaryMealCal: { fontWeight: '900', color: Colors.primary },
  dailySummaryMacroRow: {
    display: 'flex',
    gap: '10px',
    flexWrap: 'wrap',
    marginTop: '12px',
  },
  dailySummaryMacroPill: {
    flex: '1 1 80px',
    textAlign: 'center',
    padding: '8px 10px',
    borderRadius: '12px',
    fontSize: '12px',
    fontWeight: '900',
    background: '#ffffff',
    border: '1px solid #e2e8f0',
  },
  dailySummaryNet: {
    marginTop: '14px',
    paddingTop: '14px',
    borderTop: '2px solid var(--nutri-accent-alpha-15)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '8px',
  },
  dailySummaryNetLabel: { fontSize: '14px', fontWeight: '800', color: '#334155' },
  dailySummaryNetValue: { fontSize: '22px', fontWeight: '900', color: Colors.primary },
  historyBox: { background: 'white', border: '1px solid', borderRadius: '20px', overflow: 'hidden', transition: '0.3s', boxShadow: '0 8px 20px rgba(15,23,42,0.04)' },
  historyHeader: { padding: '20px 25px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  historyMealRow: { display: 'flex', justifyContent: 'space-between', padding: '10px 0', borderBottom: '1px solid #f9f9f9', fontSize: '14px' },
  historyMealType: { color: Colors.textGray, fontWeight: 'bold', minWidth: '80px' },
  historyHeroCard: { borderRadius: '32px', padding: '24px', background: Gradients.hero, color: 'white', border: 'none', boxShadow: Shadows.hero },
  historyKpiGrid: { marginTop: '16px' },
  historyKpiBox: { background: 'rgba(255,255,255,0.15)', border: '1px solid rgba(255,255,255,0.3)', borderRadius: '16px', padding: '14px 16px', backdropFilter: 'blur(2px)', display: 'flex', flexDirection: 'column', gap: '4px', fontWeight: '700' },
  historyHeroSubtext: { marginTop: '14px', fontSize: '13px', color: 'rgba(255,255,255,0.92)' },
  historyChartToggle: { display: 'flex', gap: '10px', marginBottom: '14px' },
  historyChartBtn: {
    flex: 1,
    border: '1px solid #e2e8f0',
    background: '#f8fafc',
    color: '#64748b',
    borderRadius: '12px',
    padding: '10px',
    fontWeight: '800',
    cursor: 'pointer'
  },
  historyChartBtnActive: {
    flex: 1,
    border: 'none',
    background: Gradients.primary,
    color: '#ffffff',
    borderRadius: '12px',
    padding: '10px',
    fontWeight: '800',
    cursor: 'pointer',
    boxShadow: Shadows.primary
  },
  historyChartMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    flexWrap: 'wrap',
    fontSize: '13px',
    color: Colors.textGray,
    background: Colors.bg,
    borderRadius: '12px',
    padding: '10px 12px'
  },
  historyDetailMetaRow: { display: 'flex', gap: '10px', margin: '8px 0 10px 0' },
  historyMetaPill: { fontSize: '12px', color: Colors.accent, background: Colors.accentMuted, borderRadius: '999px', padding: '4px 10px', fontWeight: '700' },
  loginPage: {
    minHeight: '100dvh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    padding: '28px',
    fontFamily: '"Sarabun", sans-serif',
    boxSizing: 'border-box',
    overflowY: 'auto',
  },
  loginOverlay: {
    position: 'absolute',
    inset: 0,
    background: Gradients.loginOverlay,
    pointerEvents: 'none',
  },
  loginShell: {
    position: 'relative',
    zIndex: 2,
    width: '100%',
    maxWidth: '980px',
    display: 'grid',
    gridTemplateColumns: '1.05fr 1fr',
    borderRadius: '28px',
    overflow: 'hidden',
    border: '1px solid rgba(255,255,255,0.22)',
    boxShadow: '0 30px 70px rgba(15, 23, 42, 0.35)'
  },
  loginBrandPanel: {
    padding: '44px 40px',
    color: '#ffffff',
    background: Gradients.loginBrand,
    backdropFilter: 'blur(4px)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    minHeight: '100%',
  },
  loginBrandTop: {
    flex: '0 1 auto',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  loginBrandThemeSlot: {
    marginTop: 'auto',
    paddingTop: '20px',
    flexShrink: 0,
    width: '100%',
    position: 'relative',
    zIndex: 5,
    overflow: 'visible',
  },
  loginBrandLogoWrap: {
    width: '56px',
    height: '56px',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(255,255,255,0.16)',
    border: '1px solid rgba(255,255,255,0.28)',
    marginBottom: '18px',
    color: '#ffffff',
  },
  loginBrandTitle: { margin: 0, fontSize: '38px', fontWeight: '900' },
  loginBrandSubtitle: { margin: '10px 0 24px 0', fontSize: '15px', lineHeight: '1.6', color: 'rgba(255,255,255,0.9)', fontWeight: '500' },
  loginFeatureList: { display: 'flex', flexDirection: 'column', gap: '12px' },
  loginFeatureItem: { display: 'flex', alignItems: 'center', gap: '10px', fontSize: '14px', fontWeight: '600', color: 'rgba(255,255,255,0.95)' },
  loginFormPanel: {
    background: 'var(--nutri-login-form-bg, rgba(255,255,255,0.96))',
    backdropFilter: 'blur(16px)',
    padding: '40px 38px',
    textAlign: 'left'
  },
  loginFormHeader: { marginBottom: '18px' },
  loginFormTitle: { margin: 0, fontSize: '28px', fontWeight: '900', color: Colors.secondary, letterSpacing: '-0.4px' },
  loginFormSub: { margin: '8px 0 0 0', fontSize: '14px', color: '#64748b', fontWeight: '500' },
  loginTabRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '8px',
    padding: '6px',
    borderRadius: '14px',
    background: '#f8fafc',
    border: '1px solid #e2e8f0',
    marginBottom: '20px'
  },
  loginTabActive: {
    border: 'none',
    borderRadius: '10px',
    padding: '10px',
    fontWeight: '800',
    fontSize: '14px',
    cursor: 'pointer',
    background: Gradients.primary,
    color: '#ffffff',
    boxShadow: Shadows.primaryBtn
  },
  loginTabInactive: {
    border: 'none',
    borderRadius: '10px',
    padding: '10px',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    background: 'transparent',
    color: '#64748b'
  },
  loginField: { marginBottom: '14px' },
  loginLabel: { display: 'block', marginBottom: '7px', fontSize: '12px', fontWeight: '800', color: '#475569', letterSpacing: '0.3px', textTransform: 'uppercase' },
  loginGrid2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' },
  loginInput: {
    width: '100%',
    padding: '13px 14px',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    marginBottom: 0,
    background: '#f8fafc',
    outline: 'none',
    boxSizing: 'border-box',
    fontSize: '14px',
    fontWeight: '600',
    color: '#0f172a'
  },
  loginFooterText: { marginTop: '18px', fontSize: '13px', color: '#64748b', textAlign: 'center' },
  loginFooterLink: {
    border: 'none',
    background: 'transparent',
    color: Colors.primary,
    cursor: 'pointer',
    fontWeight: '800',
    fontSize: '13px',
    padding: 0
  },
  btnLogin: {
    width: '100%',
    marginTop: '8px',
    padding: '14px',
    borderRadius: '12px',
    border: 'none',
    background: Gradients.primary,
    color: 'white',
    fontWeight: '900',
    fontSize: '15px',
    cursor: 'pointer',
    boxShadow: Shadows.primaryBtn
  },
  profileAvatarWrap: {
    position: 'relative',
    width: '96px',
    height: '96px',
    borderRadius: '50%',
    overflow: 'hidden',
    border: '3px solid rgba(255,255,255,0.35)',
    background: 'rgba(255,255,255,0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'transform 180ms ease, box-shadow 180ms ease'
  },
  profileAvatarImage: { width: '100%', height: '100%', objectFit: 'cover' },
  profileAvatarEditBadge: {
    position: 'absolute',
    right: '4px',
    bottom: '4px',
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    background: Colors.primary,
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '2px solid #ffffff',
    boxShadow: '0 4px 10px rgba(0,0,0,0.25)'
  },
  profileAvatarHint: {
    marginTop: '8px',
    fontSize: '11px',
    color: 'rgba(255,255,255,0.75)',
    textAlign: 'center',
    fontWeight: '600'
  },
  avatarModalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(15, 23, 42, 0.72)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '24px'
  },
  avatarModalCard: {
    position: 'relative',
    width: '100%',
    maxWidth: '520px',
    background: '#ffffff',
    borderRadius: '24px',
    padding: '18px',
    boxShadow: '0 24px 60px rgba(15, 23, 42, 0.35)'
  },
  avatarModalCloseBtn: {
    position: 'absolute',
    top: '12px',
    right: '12px',
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    border: 'none',
    background: '#f1f5f9',
    color: '#334155',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer'
  },
  avatarModalImage: {
    width: '100%',
    maxHeight: '62vh',
    objectFit: 'contain',
    borderRadius: '16px',
    background: '#f8fafc'
  },
  avatarModalActions: {
    marginTop: '14px',
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '10px'
  },
  avatarModalChangeBtn: {
    border: '1px solid #e2e8f0',
    background: '#f8fafc',
    color: '#334155',
    borderRadius: '12px',
    padding: '11px',
    fontWeight: '800',
    cursor: 'pointer'
  },
  avatarModalDeleteBtn: {
    border: '1px solid #fecaca',
    background: '#fff1f2',
    color: '#dc2626',
    borderRadius: '12px',
    padding: '11px',
    fontWeight: '800',
    cursor: 'pointer'
  },
  btnEditCircle: { background: Colors.primary, color: 'white', border: 'none', width: '40px', height: '40px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' },
  btnSave: { background: Colors.success, color: 'white', border: 'none', padding: '8px 20px', borderRadius: '12px', fontWeight: 'bold', cursor: 'pointer' },
  profileInfoRow: { display: 'flex', justifyContent: 'space-between', padding: '12px 0', borderBottom: '1px solid #f5f5f5' },
  inlineInput: { width: '80px', padding: '5px', borderRadius: '8px', border: `1px solid ${Colors.border}`, textAlign: 'center' },
  tdeeBox: { background: Colors.bg, padding: '20px', borderRadius: '20px', textAlign: 'center', marginTop: '15px' },
  themePickerWrap: {
    marginBottom: '18px',
    padding: '16px',
    borderRadius: '16px',
    background: Colors.white,
    border: `1px solid ${Colors.border}`,
    boxShadow: '0 1px 3px rgba(15,23,42,0.06)',
  },
  themePickerWrapCompact: {
    marginBottom: 0,
    padding: '12px',
    borderRadius: '14px',
  },
  themeFabRoot: {
    position: 'relative',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '8px',
    zIndex: 5,
  },
  themeFabShell: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  themeFabPanel: {
    overflow: 'hidden',
    width: 'min(100%, 300px)',
    padding: 0,
    marginBottom: 0,
    borderRadius: '18px',
  },
  themeFabPanelHeader: {
    marginBottom: '10px',
    textAlign: 'center',
    width: '100%',
  },
  themeFabTrigger: {
    width: '56px',
    height: '56px',
    borderRadius: '999px',
    border: '3px solid rgba(255,255,255,0.85)',
    background: 'var(--nutri-gradient-primary)',
    boxShadow: 'var(--nutri-shadow-primary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    padding: 0,
    flexShrink: 0,
    overflow: 'hidden',
  },
  themeFabHint: {
    margin: 0,
    fontSize: '11px',
    fontWeight: '600',
    color: 'rgba(255,255,255,0.82)',
    lineHeight: 1.35,
    paddingLeft: '4px',
  },
  themePickerModalHint: {
    margin: '4px 0 0 0',
    fontSize: '12px',
    fontWeight: '600',
    lineHeight: 1.4,
  },
  themePickerModal: {
    width: '100%',
    maxWidth: '360px',
    maxHeight: 'min(90vh, 640px)',
    overflowY: 'auto',
    padding: '16px',
    borderRadius: '18px',
  },
  themePickerModalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    marginBottom: '12px',
  },
  themePickerModalClose: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '34px',
    height: '34px',
    borderRadius: '10px',
    border: 'none',
    background: '#F1F5F9',
    color: '#64748B',
    cursor: 'pointer',
  },
  themePickerModalDone: {
    width: '100%',
    marginTop: '12px',
    padding: '12px',
    borderRadius: '12px',
    border: 'none',
    background: 'var(--nutri-primary)',
    color: '#FFFFFF',
    fontSize: '14px',
    fontWeight: '800',
    cursor: 'pointer',
    boxShadow: 'var(--nutri-shadow-primary-soft)',
  },
  themePickerTitleCompact: {
    fontSize: '13px',
    fontWeight: '700',
    marginBottom: 0,
  },
  themeModeToggleCompact: {
    display: 'flex',
    gap: '3px',
    padding: '3px',
    borderRadius: '10px',
    flexShrink: 0,
  },
  themeModeBtnCompact: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '30px',
    height: '28px',
    padding: 0,
    borderRadius: '7px',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    transition: 'background 0.15s ease, color 0.15s ease',
  },
  themePickerGridCompact: {
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: '5px',
    marginBottom: '8px',
  },
  themePickerGridExpanded: {
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: '5px',
    marginBottom: '8px',
  },
  themePickerTileCompact: {
    padding: '5px',
    borderRadius: '10px',
    minHeight: 0,
    aspectRatio: '1',
  },
  themePickerBadgeCompact: {
    position: 'absolute',
    top: '3px',
    right: '3px',
    width: '16px',
    height: '16px',
    borderRadius: '999px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  themePickerSectionLabel: {
    margin: '0 0 8px 0',
    fontSize: '12px',
    fontWeight: '800',
    letterSpacing: '0.2px',
  },
  themePickerExpandBtn: {
    display: 'block',
    width: '100%',
    marginTop: '2px',
    padding: '4px 0 0',
    border: 'none',
    background: 'transparent',
    fontSize: '11px',
    fontWeight: '600',
    cursor: 'pointer',
    textAlign: 'center',
    opacity: 0.85,
  },
  themePickerWrapBrand: {
    marginBottom: 0,
    padding: '14px',
    background: 'rgba(255,255,255,0.14)',
    border: '1px solid rgba(255,255,255,0.24)',
    boxShadow: '0 8px 24px rgba(15,23,42,0.12)',
    backdropFilter: 'blur(10px)',
  },
  themePickerTitle: {
    fontSize: '14px',
    fontWeight: '700',
    color: Colors.textDark,
    marginBottom: '12px',
  },
  themePickerTitleBrand: {
    color: '#FFFFFF',
  },
  themePickerGridBrand: {
    gap: '6px',
    marginBottom: '12px',
  },
  themePickerTileBrand: {
    padding: '8px',
    borderRadius: '12px',
  },
  themePickerCustomInnerBrand: {
    width: '44px',
    height: '44px',
  },
  themeFollowLabelBrand: {
    color: 'rgba(255,255,255,0.95)',
  },
  themeModeToggle: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: '6px',
    marginBottom: '14px',
    padding: '4px',
    borderRadius: '12px',
    background: Colors.bgSoft,
    border: `1px solid ${Colors.border}`,
  },
  themeModeBtn: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    padding: '8px 6px',
    borderRadius: '9px',
    border: 'none',
    background: 'transparent',
    color: Colors.textGray,
    fontSize: '12px',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'background 0.15s ease, color 0.15s ease',
  },
  themeModeBtnActive: {
    background: '#2563EB',
    color: '#FFFFFF',
    boxShadow: '0 2px 8px rgba(37,99,235,0.28)',
  },
  themeModeBtnDisabled: {
    opacity: 0.45,
    cursor: 'not-allowed',
  },
  themeModeCheck: {
    position: 'absolute',
    top: '4px',
    right: '4px',
    width: '16px',
    height: '16px',
    borderRadius: '999px',
    background: 'rgba(255,255,255,0.22)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  themePickerGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: '8px',
    marginBottom: '14px',
  },
  themePickerTile: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    aspectRatio: '1',
    padding: '10px',
    borderRadius: '14px',
    border: `1px solid ${Colors.border}`,
    background: Colors.bgSoft,
    cursor: 'pointer',
    transition: 'border-color 0.15s ease, box-shadow 0.15s ease',
  },
  themePickerTileActive: {
    border: '2px solid #2563EB',
    boxShadow: '0 0 0 1px rgba(37,99,235,0.12)',
    background: Colors.white,
  },
  themePreviewCircle: {
    position: 'relative',
    borderRadius: '999px',
    overflow: 'hidden',
    boxShadow: '0 1px 4px rgba(15,23,42,0.12)',
    flexShrink: 0,
  },
  themePreviewTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '50%',
  },
  themePreviewBottomLeft: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '50%',
    height: '50%',
  },
  themePreviewBottomRight: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: '50%',
    height: '50%',
  },
  themePickerBadge: {
    position: 'absolute',
    top: '6px',
    right: '6px',
    width: '22px',
    height: '22px',
    borderRadius: '999px',
    background: '#2563EB',
    color: '#FFFFFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 2px 6px rgba(37,99,235,0.35)',
  },
  themePickerCustomInner: {
    width: '52px',
    height: '52px',
    borderRadius: '999px',
    background: Colors.white,
    border: `1px dashed ${Colors.border}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  themePickerColorInput: {
    position: 'absolute',
    width: 0,
    height: 0,
    opacity: 0,
    pointerEvents: 'none',
  },
  themeFollowRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    paddingTop: '4px',
    cursor: 'pointer',
  },
  themeFollowLabel: {
    fontSize: '13px',
    fontWeight: '600',
    color: Colors.textDark,
  },
  themeFollowSwitchWrap: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
  },
  themeFollowSwitchInput: {
    position: 'absolute',
    opacity: 0,
    width: 0,
    height: 0,
  },
  themeFollowSwitchTrack: {
    width: '44px',
    height: '24px',
    borderRadius: '999px',
    background: '#CBD5E1',
    position: 'relative',
    transition: 'background 0.2s ease',
  },
  themeFollowSwitchTrackOn: {
    background: '#2563EB',
  },
  themeFollowSwitchThumb: {
    position: 'absolute',
    top: '3px',
    left: '3px',
    width: '18px',
    height: '18px',
    borderRadius: '999px',
    background: '#FFFFFF',
    boxShadow: '0 1px 3px rgba(15,23,42,0.2)',
    transition: 'transform 0.2s ease',
  },
  themeFollowSwitchThumbOn: {
    transform: 'translateX(20px)',
  },
  themePickerLabel: {
    fontSize: '12px',
    fontWeight: '800',
    color: Colors.textGray,
    textTransform: 'uppercase',
    letterSpacing: '0.4px',
    marginBottom: '10px',
  },
  themePickerCompact: {
    marginBottom: '14px',
  },
  themePickerOption: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '8px',
    padding: '10px',
    borderRadius: '12px',
    border: `1px solid ${Colors.border}`,
    background: Colors.white,
    cursor: 'pointer',
    textAlign: 'left',
  },
  themePickerOptionActive: {
    border: '2px solid var(--nutri-primary)',
    boxShadow: 'var(--nutri-shadow-primary-soft)',
  },
  themePickerSwatches: {
    display: 'flex',
    gap: '6px',
  },
  themePickerSwatch: {
    width: '22px',
    height: '22px',
    borderRadius: '999px',
    border: '2px solid #ffffff',
    boxShadow: '0 0 0 1px rgba(15,23,42,0.08)',
  },
  themePickerName: {
    fontSize: '12px',
    fontWeight: '900',
    color: Colors.textDark,
    lineHeight: 1.3,
  },
  themePickerDesc: {
    fontSize: '10px',
    fontWeight: '600',
    color: Colors.textGray,
    lineHeight: 1.35,
  },
};
